### ISSUE TITLE
Bug with babelify and bankai

### ISSUE THREAD

**Issue by auggod** [depackt/depackt-map#5]
Trying to use es6 import/export for client code.

`SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (8:0) while parsing file: /Users/auggod/depackt/develop/web/depackt-map/app/client/index.js
    at Parser.pp.raise (/Users/auggod/depackt/develop/web/depackt-map/node_modules/falafel/node_modules/acorn/dist/acorn.js:1745:13)
    at Parser.pp.parseStatement (/Users/auggod/depackt/develop/web/depackt-map/node_modules/falafel/node_modules/acorn/dist/acorn.js:2450:34)
    at Parser.pp.parseTopLevel (/Users/auggod/depackt/develop/web/depackt-map/node_modules/falafel/node_modules/acorn/dist/acorn.js:2379:21)
    at parse (/Users/auggod/depackt/develop/web/depackt-map/node_modules/falafel/node_modules/acorn/dist/acorn.js:101:12)
    at module.exports (/Users/auggod/depackt/develop/web/depackt-map/node_modules/falafel/index.js:22:15)
    at DestroyableTransform.end [as _flush] (/Users/auggod/depackt/develop/web/depackt-map/node_modules/sheetify/transform.js:58:22)
    at DestroyableTransform.<anonymous> (/Users/auggod/depackt/develop/web/depackt-map/node_modules/readable-stream/lib/_stream_transform.js:138:49)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at DestroyableTransform.emit (events.js:207:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! depackt-map@1.0.0 start: `babel-node ./index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the depackt-map@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/auggod/.npm/_logs/2017-07-15T10_41_31_812Z-debug.log
➜  depackt-map debug/bankai-babelify ✓`

**Comment by auggod** [comment]
https://github.com/choojs/bankai/issues/208

**Comment by auggod** [comment]
Made a new branch for testing: https://github.com/depackt/depackt-map/tree/debug/bankai-babelify
Babelify config: https://github.com/depackt/depackt-map/blob/debug/bankai-babelify/app/server/index.js#L42
Client: https://github.com/depackt/depackt-map/blob/debug/bankai-babelify/app/client/index.js#L8
